name: linter

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.19.0'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Laravel Pint (PHP Linter)
        run: vendor/bin/pint

      - name: Format Frontend (Prettier)
        run: pnpm run format

      - name: Lint Frontend (ESLint)
        run: pnpm run lint

      # Si deseas que automáticamente se hagan commits cuando Pint o Prettier formateen archivos:
      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: 'style: auto-format by CI'
      #     commit_options: '--no-verify'
      #     branch: ${{ github.head_ref }}
